# Generated by Django 3.0.8 on 2020-07-28 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popularity', models.DecimalField(blank=True, decimal_places=10, max_digits=19)),
                ('director', models.CharField(blank=True, max_length=200)),
                ('imdb_score', models.DecimalField(blank=True, decimal_places=10, max_digits=19)),
                ('movie_title', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_title', models.CharField(blank=True, max_length=1000)),
                ('moviedetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.MovieDetails')),
            ],
        ),
    ]
